// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLibrary(arg1) {
  return window['go']['main']['App']['AddLibrary'](arg1);
}

export function DeleteGame(arg1) {
  return window['go']['main']['App']['DeleteGame'](arg1);
}

export function GetState(arg1) {
  return window['go']['main']['App']['GetState'](arg1);
}

export function LaunchGame(arg1) {
  return window['go']['main']['App']['LaunchGame'](arg1);
}

export function RemoveLibrary(arg1) {
  return window['go']['main']['App']['RemoveLibrary'](arg1);
}

export function ScanLibraries() {
  return window['go']['main']['App']['ScanLibraries']();
}

export function ScrapeMetadataForGame(arg1) {
  return window['go']['main']['App']['ScrapeMetadataForGame'](arg1);
}

export function SetGameDeleted(arg1, arg2) {
  return window['go']['main']['App']['SetGameDeleted'](arg1, arg2);
}

export function UpdateGameMetadata(arg1, arg2) {
  return window['go']['main']['App']['UpdateGameMetadata'](arg1, arg2);
}
