// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function AddLibrary(arg1:string):Promise<void>;

export function DeleteGame(arg1:string):Promise<void>;

export function GetState(arg1:boolean):Promise<model.AppState>;

export function LaunchGame(arg1:string):Promise<void>;

export function RemoveLibrary(arg1:string):Promise<void>;

export function ScanLibraries():Promise<Array<model.Game>>;

export function ScrapeMetadataForGame(arg1:string):Promise<model.Game>;

export function SetGameDeleted(arg1:string,arg2:boolean):Promise<void>;

export function UpdateGameMetadata(arg1:string,arg2:model.GameMetadataUpdate):Promise<model.Game>;
